### ISSUE TITLE
KeyError: 'ProfilePage'

### ISSUE THREAD

**Issue by Cava15** [yezz123/SoIG#4]
Hi,

Sorry if the error is "noob error" im just starting in Linux.

i'm running in Kali Linux 2020.4 and when i install and i give the permissions i start to search my username and error outputs:
File "main.py", line 16, in <module>
    ig = main(user=args["username"])
  File "/home/kali/Desktop/SoIG/.lib/api.py", line 62, in __init__
    self.get_profile()
  File "/home/kali/Desktop/SoIG/.lib/api.py", line 70, in get_profile
    self.p_data = self.data['entry_data']['ProfilePage'][0]['graphql']['user']
KeyError: 'ProfilePage'

Can any one help me to understand this issue or/and solve?
Thanks in advance

**Comment by yezz123** [comment]
I guess your account is on private mode!
And am working on private account to show it!
This tool is work only with public account

**Comment by Cava15** [comment]
Hi,

You mean thant private profile on instagram can't recollect info? If it's, i tried with public account and happens the same issue.

**Comment by yezz123** [comment]
Please!
Give me more information about your system.

**Comment by Scirocco10** [comment]
Love the Repo - Thanks
Im getting same error***Any work around?
[+] getting profile ...Traceback (most recent call last):
  File "main.py", line 16, in <module>
    ig = main(user=args["username"])
  File "/home/runner/SoIG/SoIG/.lib/api.py", line 58, in __init__
    self.get_profile()
  File "/home/runner/SoIG/SoIG/.lib/api.py", line 66, in get_profile
    self.p_data = self.data['entry_data']['ProfilePage'][0]['graphql']['user']
KeyError: 'ProfilePage'

**Comment by yezz123** [comment]
I guess the Profile Doesn’t exist or the API didn't handle the full request some times it shows some buggies, I just test in a different env its work smoothly 🚀
